#!/bin/bash
cd ${0%/*}
cd ..

url='https://raw.githubusercontent.com/ChDC/ChDCNovelReader/dev/'

git checkout dev && cordova-hcp build && python tools/ReplaceCRLFtoLF.py -d www && git add . && git commit -m "Update Resources" && git push github dev && python tools/RefreshGithubURL.py -d www -u $url
